SystemExit in line 21 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v7/test.smk:
ERROR: Unusual number of reads detected
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v7/test.smk", line 26, in <module>
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v7/test.smk", line 21, in parse_samples
  File "/home/thkuo/miniconda3/envs/seq2geno/lib/python3.6/_sitebuiltins.py", line 26, in __call__
