Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	create_and_make_expr_table
	1	create_indel_table
	1	vcf_to_indels
	4

rule vcf_to_indels:
    input: tmp/indels/vcf.list, core_genes_50.txt
    output: tmp/indels/indel.list
    jobid: 9
    wildcards: TMP_D=tmp

    Error in rule vcf_to_indels:
        jobid: 9
        output: tmp/indels/indel.list

RuleException:
CalledProcessError in line 111 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/CREATE_INDEL_TABLE.smk:
Command ' set -euo pipefail;  cd tmp/indels;cat /net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/core_genes_50.txt | while read i;do echo "java -jar indel_detection/vcf2indel.py < /net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/tmp/extracted_protein_nt/${i}.aln.fasta> ${i}.vcf";done;cd /net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3;ls tmp/indels|grep indels.txt$ > tmp/indels/indel.list ' returned non-zero exit status 1.
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/CREATE_INDEL_TABLE.smk", line 111, in __rule_vcf_to_indels
  File "/home/thkuo/miniconda3/envs/phypal/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Removing output files of failed job vcf_to_indels since they might be corrupted:
tmp/indels/indel.list
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/.snakemake/log/2018-07-12T162819.222099.snakemake.log
