Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	create_indel_table
	1	expand_by_family
	3	vcf_to_indels_per_fam
	6

[Mon Aug 13 11:13:48 2018]
rule vcf_to_indels_per_fam:
    input: tmp/extracted_proteins_nt/aaaT.vcf
    output: tmp/extracted_proteins_nt/aaaT_indels.txt, tmp/extracted_proteins_nt/aaaT_indels.gff, tmp/extracted_proteins_nt/aaaT_indel_stats.txt
    jobid: 20
    wildcards: fam=aaaT

    [Mon Aug 13 11:13:48 2018]
    Error in rule vcf_to_indels_per_fam:
        jobid: 20
        output: tmp/extracted_proteins_nt/aaaT_indels.txt, tmp/extracted_proteins_nt/aaaT_indels.gff, tmp/extracted_proteins_nt/aaaT_indel_stats.txt

RuleException:
CalledProcessError in line 53 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v4/CREATE_INDEL_TABLE.smk:
Command ' set -euo pipefail;  /home/thkuo/miniconda3/envs/phypal/bin/python /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v4/indel_detection/.snakemake.lxo_lp9w.vcf2indel.py ' returned non-zero exit status 1.
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v4/CREATE_INDEL_TABLE.smk", line 53, in __rule_vcf_to_indels_per_fam
  File "/home/thkuo/miniconda3/envs/phypal/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v4/.snakemake/log/2018-08-13T111346.634319.snakemake.log
