Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	aln_to_vcf
	1	create_and_make_expr_table
	1	create_indel_table
	1	filter_genes
	1	vcf_to_indels
	6

rule filter_genes:
    input: tmp/roary/gene_presence_absence.csv
    output: core_genes_50.txt
    jobid: 10

Finished job 10.
1 of 6 steps (17%) done

rule aln_to_vcf:
    input: core_genes_50.txt
    output: tmp/indels/vcf.list
    jobid: 11
    wildcards: TMP_D=tmp

    Error in rule aln_to_vcf:
        jobid: 11
        output: tmp/indels/vcf.list

RuleException:
CalledProcessError in line 83 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/CREATE_INDEL_TABLE.smk:
Command ' set -euo pipefail;  cd tmp/indels;cat ../../core_genes_50.txt | while read i;do echo "java -jar jvarkit/dist/msa2vcf.jar < ../extracted_protein_nt/${i}.aln.fasta> ${i}.vcf";done;cd ../../;ls tmp/indels|grep vcf$ > tmp/indels/vcf.list ' returned non-zero exit status 1.
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/CREATE_INDEL_TABLE.smk", line 83, in __rule_aln_to_vcf
  File "/home/thkuo/miniconda3/envs/phypal/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/.snakemake/log/2018-07-12T161139.907035.snakemake.log
