Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	create_and_make_expr_table
	1	write_dict_file
	3

[Fri Aug 24 17:07:54 2018]
rule write_dict_file:
    input: tmp/CH2500/rna_sorted.rmdup.rpg, tmp/CH2502/rna_sorted.rmdup.rpg, tmp/CH2522/rna_sorted.rmdup.rpg, tmp/F1659/rna_sorted.rmdup.rpg
    output: tmp/rpg_dict
    jobid: 5

    [Fri Aug 24 17:07:54 2018]
    Error in rule write_dict_file:
        jobid: 5
        output: tmp/rpg_dict

RuleException:
CalledProcessError in line 239 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v5/CREATE_EXPR_TABLE.smk:
Command ' set -euo pipefail;  
        echo 'name  path' > tmp/rpg_dict
        ls tmp/*/rna_sorted.rmdup.rpg|        -v pwd=$PWD -F"/" '{print $2"	"pwd"/"$0}' >> tmp/rpg_dict ' returned non-zero exit status 127.
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v5/CREATE_EXPR_TABLE.smk", line 239, in __rule_write_dict_file
  File "/home/thkuo/miniconda3/envs/seq2geno/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job write_dict_file since they might be corrupted:
tmp/rpg_dict
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v5/.snakemake/log/2018-08-24T170750.538748.snakemake.log
