Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	create_indel_table
	1	expand_by_family
	5	vcf_to_indels_per_fam
	8

[Tue Aug 14 15:25:50 2018]
rule vcf_to_indels_per_fam:
    input: tmp/extracted_proteins_nt/fhuA_3.vcf
    output: tmp/extracted_proteins_nt/fhuA_3_indels.txt, tmp/extracted_proteins_nt/fhuA_3_indels.gff, tmp/extracted_proteins_nt/fhuA_3_indel_stats.txt
    jobid: 24
    wildcards: fam=fhuA_3

    [Tue Aug 14 15:25:51 2018]
    Error in rule vcf_to_indels_per_fam:
        jobid: 24
        output: tmp/extracted_proteins_nt/fhuA_3_indels.txt, tmp/extracted_proteins_nt/fhuA_3_indels.gff, tmp/extracted_proteins_nt/fhuA_3_indel_stats.txt

RuleException:
CalledProcessError in line 48 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v4/CREATE_INDEL_TABLE.smk:
Command ' set -euo pipefail;  /home/thkuo/miniconda3/envs/seq2geno/bin/python /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v4/lib/indel_detection/.snakemake.ri6os0y1.vcf2indel.py ' returned non-zero exit status 1.
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v4/CREATE_INDEL_TABLE.smk", line 48, in __rule_vcf_to_indels_per_fam
  File "/home/thkuo/miniconda3/envs/seq2geno/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v4/.snakemake/log/2018-08-14T152547.210681.snakemake.log
