Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	all_snps_table
	1	nonsyn_snps_table
	1	syn_snps_table
	4

[Thu Aug 16 11:11:54 2018]
rule all_snps_table:
    input: tmp/CH2500/bwa/variant.flatcount, tmp/CH2502/bwa/variant.flatcount, tmp/CH2522/bwa/variant.flatcount, tmp/F1659/bwa/variant.flatcount, tmp/CH2500/bwa/variant.snp-vcf, tmp/CH2502/bwa/variant.snp-vcf, tmp/CH2522/bwa/variant.snp-vcf, tmp/F1659/bwa/variant.snp-vcf, strain_list, Pseudomonas_aeruginosa_PA14_annotation_with_ncRNAs_07_2011_12genes.tab
    output: tmp/all_SNPs.tab
    jobid: 3

    [Thu Aug 16 11:11:57 2018]
    Error in rule all_snps_table:
        jobid: 3
        output: tmp/all_SNPs.tab

RuleException:
CalledProcessError in line 52 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v4/CREATE_SNPS_TABLE.smk:
Command ' set -euo pipefail;  
        source activate py27
        python lib/mutation_table.v5.py  -f strain_list         -a Pseudomonas_aeruginosa_PA14_annotation_with_ncRNAs_07_2011_12genes.tab -o tmp/all_SNPs.tab
        source deactivate ' returned non-zero exit status 1.
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v4/CREATE_SNPS_TABLE.smk", line 52, in __rule_all_snps_table
  File "/home/thkuo/miniconda3/envs/seq2geno/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v4/.snakemake/log/2018-08-16T111150.712936.snakemake.log
