Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	nonsyn_snps_table
	1	syn_snps_table
	3

rule syn_snps_table:
    input: tmp/all_SNPs.tab, /net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/data/reference/RefCln_UCBPP-PA14.gbk
    output: /net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/results/syn_snps.tab
    jobid: 2

Terminating processes on user request, this might take some time.
    Error in rule syn_snps_table:
        jobid: 2
        output: /net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/results/syn_snps.tab

RuleException:
CalledProcessError in line 35 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/CREATE_SNPS_TABLE.smk:
Command ' set -euo pipefail;  source activate py27;python ./Snp2Amino.v2.py -f tmp/all_SNPs.tab -g /net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/data/reference/RefCln_UCBPP-PA14.gbk -n all -o /net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/results/syn_snps.tab ;source deactivate ' returned non-zero exit status 1.
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/CREATE_SNPS_TABLE.smk", line 35, in __rule_syn_snps_table
  File "/home/thkuo/miniconda3/envs/phypal/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Complete log: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/.snakemake/log/2018-07-12T112452.739984.snakemake.log
