Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	filter_genes
	1	sort_gene_family
	3

rule filter_genes:
    input: tmp/roary/gene_presence_absence.csv
    output: core_genes_50.txt
    jobid: 6

Finished job 6.
1 of 3 steps (33%) done

rule sort_gene_family:
    input: core_genes_50.txt, tmp/roary/clustered_proteins, tmp/prokka/CH2500/CH2500.ffn, tmp/prokka/CH2502/CH2502.ffn, tmp/prokka/CH2522/CH2522.ffn, tmp/prokka/F1659/F1659.ffn
    output: tmp/extracted_protein_nt/families.list
    jobid: 1
    wildcards: TMP_D=tmp, extracted_proteins_dir=extracted_protein_nt

    Error in rule sort_gene_family:
        jobid: 1
        output: tmp/extracted_protein_nt/families.list

RuleException:
CalledProcessError in line 32 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/CREATE_INDEL_TABLE.smk:
Command ' set -euo pipefail;  /home/thkuo/miniconda3/envs/phypal/bin/python /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/.snakemake.na01qtrr.makeGroupAln.py ' returned non-zero exit status 1.
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/CREATE_INDEL_TABLE.smk", line 32, in __rule_sort_gene_family
  File "/home/thkuo/miniconda3/envs/phypal/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/.snakemake/log/2018-07-13T155311.932183.snakemake.log
