Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	aln_to_vcf_per_fam
	1	compress_feat_table
	1	create_indel_table
	1	expand_by_family
	1	sort_gene_family
	1	vcf_to_indels_per_fam
	7

[Tue Sep  4 11:55:56 2018]
rule sort_gene_family:
    input: seq2geno_temp/roary/gene_presence_absence.csv, seq2geno_temp/CH2500/spades/prokka/de_novo.ffn, seq2geno_temp/CH2502/spades/prokka/de_novo.ffn, seq2geno_temp/CH2522/spades/prokka/de_novo.ffn, seq2geno_temp/F1659/spades/prokka/de_novo.ffn, seq2geno_temp/ESP088/spades/prokka/de_novo.ffn, seq2geno_temp/MHH15083/spades/prokka/de_novo.ffn
    output: seq2geno_temp/extracted_proteins_nt/{*}.aln (dynamic)
    jobid: 75

Subsequent jobs will be added dynamically depending on the output of this job
    [Tue Sep  4 11:57:45 2018]
    Error in rule sort_gene_family:
        jobid: 75
        output: seq2geno_temp/extracted_proteins_nt/{*}.aln (dynamic)

RuleException:
CalledProcessError in line 16 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v5/CREATE_INDEL_TABLE.smk:
Command ' set -euo pipefail;  /home/thkuo/miniconda3/envs/seq2geno/bin/python /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v5/lib/.snakemake.yw4pjpcl.makeGroupAln.py ' returned non-zero exit status 1.
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v5/CREATE_INDEL_TABLE.smk", line 16, in __rule_sort_gene_family
  File "/home/thkuo/miniconda3/envs/seq2geno/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v5/.snakemake/log/2018-09-04T114606.854921.snakemake.log
