Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	all_snps_table
	1	nonsyn_snps_table
	1	syn_snps_table
	4

rule all_snps_table:
    input: tmp/CH2500/bwa.flatcount, tmp/CH2502/bwa.flatcount, tmp/CH2522/bwa.flatcount, tmp/F1659/bwa.flatcount, tmp/CH2500/bwa.snp-vcf, tmp/CH2502/bwa.snp-vcf, tmp/CH2522/bwa.snp-vcf, tmp/F1659/bwa.snp-vcf, strain_list, Pseudomonas_aeruginosa_PA14_annotation_with_ncRNAs_07_2011_12genes.tab
    output: tmp/all_SNPs.tab
    jobid: 4

    Error in rule all_snps_table:
        jobid: 4
        output: tmp/all_SNPs.tab

RuleException:
CalledProcessError in line 22 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/CREATE_SNPS_TABLE.smk:
Command ' set -euo pipefail;  source activate py27;python ./mutation_table.v4.py  -f strain_list -a Pseudomonas_aeruginosa_PA14_annotation_with_ncRNAs_07_2011_12genes.tab -o tmp/all_SNPs.tab;source deactivate ' returned non-zero exit status 1.
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/CREATE_SNPS_TABLE.smk", line 22, in __rule_all_snps_table
  File "/home/thkuo/miniconda3/envs/phypal/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/.snakemake/log/2018-07-12T110514.218327.snakemake.log
