Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	aln_to_vcf
	1	create_indel_table
	1	make_gene_family_alignment
	1	vcf_to_indels
	5

rule make_gene_family_alignment:
    input: tmp/extracted_protein_nt/families.list
    output: tmp/extracted_protein_nt/families_aln.list
    jobid: 32
    wildcards: TMP_D=tmp

    Error in rule make_gene_family_alignment:
        jobid: 32
        output: tmp/extracted_protein_nt/families_aln.list

RuleException:
CalledProcessError in line 64 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/CREATE_INDEL_TABLE.smk:
Command ' set -euo pipefail;  cd tmp/extracted_protein_nt; parallel -j 16 'mafft {}.fasta > {}.aln.fasta':::\`ls| grep fasta| cut -f1 -d "."\`cd /net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3;ls tmp/indels|grep aln\.fasta$ > tmp/extracted_protein_nt/families_aln.list ' returned non-zero exit status 1.
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/CREATE_INDEL_TABLE.smk", line 64, in __rule_make_gene_family_alignment
  File "/home/thkuo/miniconda3/envs/phypal/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/.snakemake/log/2018-07-12T224415.474813.snakemake.log
